name = "spin-mama-bonus-org"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-bonus.org"
HMAC_KEY = "10e6d1b7a3b0a8b9609e3d74c66f144af6abe01514a10aead6bf080396bfb4a6"
COOKIE_NAME = "apr"
PLAY_PATH = "explore"
BUTTON_ID = "pa1ffe1d848358c066aa489da72fb4685"
GATE_SALT = "ca23294b9e69c953"
